### ISSUE TITLE
webpack.dev.config.rs error

### ISSUE THREAD

**Issue by jimmythecode** [carlrip/react-typescript-eslint-webpack#1]
I followed the guide here: https://www.carlrippon.com/creating-react-app-with-typescript-eslint-with-webpack5/

My linter flagged an error ```  'devServer' does not exist in type 'Configuration' ``` , which also prevented me running ``` npm start ```. The following resolved it:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/27570#issuecomment-474628163

**Comment by carlrip** [comment]
Updated `webpack.dev.config.ts` with the suggested fix from above
